import { createHash } from 'node:crypto';

export const PAGE_SIZE = 100;
export const digest = (text) => createHash('sha256').update(text).digest('hex');

/** One generator for production and scale checks. Output paths are repository-relative. */
export function generateCatalog(entries, write) {
  const sorted = [...entries].sort((a, b) => a.id.localeCompare(b.id));
  const manifest = {
    generated_note: 'GENERATED by scripts/build.mjs; do not edit.',
    schema_version: 1, count: sorted.length, page_size: PAGE_SIZE,
    pages: [], facets: { category: {}, outcome: {}, tag: {}, project: {} },
  };
  const pages = (rows, prefix) => {
    const result = [];
    for (let n = 0; n < rows.length; n += PAGE_SIZE) {
      const path = `${prefix}/${String(n / PAGE_SIZE + 1).padStart(5, '0')}.json`;
      const text = JSON.stringify({ schema_version: 1, ideas: rows.slice(n, n + PAGE_SIZE) }, null, 2) + '\n';
      write(path, text);
      result.push({ path, count: Math.min(PAGE_SIZE, rows.length - n), bytes: Buffer.byteLength(text), sha256: digest(text) });
    }
    return result;
  };
  manifest.pages = pages(sorted, 'catalog/pages');
  for (const axis of Object.keys(manifest.facets)) {
    const groups = new Map();
    for (const item of sorted) {
      const values = axis === 'tag' ? item.tags : axis === 'project' ? item.projects : [item[axis]];
      for (const value of new Set(values || [])) {
        if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value)) throw new Error(`Invalid ${axis} facet`);
        if (!groups.has(value)) groups.set(value, []);
        groups.get(value).push(item);
      }
    }
    for (const [value, rows] of [...groups].sort(([a], [b]) => a.localeCompare(b))) {
      manifest.facets[axis][value] = { count: rows.length, pages: pages(rows, `catalog/${axis}/${value}`) };
    }
  }
  for (const item of sorted) {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(item.id)) throw new Error('Invalid idea ID');
    write(`catalog/ideas/${item.id}.json`, JSON.stringify(item, null, 2) + '\n');
  }
  write('catalog/manifest.json', JSON.stringify(manifest, null, 2) + '\n');
  return manifest;
}
