/** Shared loader: taxonomy, sources, and every idea.md in the tree. */

import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseFile, FrontmatterError } from './frontmatter.mjs';

export const ROOT = fileURLToPath(new URL('../..', import.meta.url));

export function readJSON(p) {
  return JSON.parse(readFileSync(join(ROOT, p), 'utf8'));
}

export function loadTaxonomy() {
  const t = readJSON('data/taxonomy.json');
  const tagAxis = new Map();
  for (const axis of ['domain', 'mechanic', 'stage']) {
    for (const tag of t.tags[axis]) tagAxis.set(tag.id, axis);
  }
  return {
    raw: t,
    outcomes: new Set(t.outcomes.map((o) => o.id)),
    outcomeMeta: new Map(t.outcomes.map((o) => [o.id, o])),
    effort: new Set(t.effort.map((e) => e.id)),
    confidence: new Set(t.confidence.map((c) => c.id)),
    categories: t.categories,
    categoryIds: new Set(t.categories.map((c) => c.id)),
    categoryMeta: new Map(t.categories.map((c) => [c.id, c])),
    tagAxis,
    tagDefs: new Map(
      ['domain', 'mechanic', 'stage'].flatMap((a) => t.tags[a].map((x) => [x.id, { ...x, axis: a }]))
    ),
    aliases: t.aliases || {},
  };
}

export function loadSources() {
  return readJSON('data/sources.json');
}

/** Every idea folder on disk, parsed. Order is stable (category, then id). */
export function loadIdeas() {
  const ideasDir = join(ROOT, 'ideas');
  const out = [];
  if (!existsSync(ideasDir)) return out;

  for (const cat of readdirSync(ideasDir, { withFileTypes: true })) {
    if (!cat.isDirectory()) continue;
    const catDir = join(ideasDir, cat.name);
    for (const slug of readdirSync(catDir, { withFileTypes: true })) {
      if (!slug.isDirectory()) continue;
      const dir = join(catDir, slug.name);
      const file = join(dir, 'idea.md');
      if (!existsSync(file)) {
        out.push({ _error: 'no idea.md in this folder', dir: rel(dir), slugDir: slug.name, catDir: cat.name });
        continue;
      }
      let parsed;
      try {
        parsed = parseFile(readFileSync(file, 'utf8'));
      } catch (e) {
        out.push({
          _error: e instanceof FrontmatterError ? e.message : String(e),
          dir: rel(dir), file: rel(file), slugDir: slug.name, catDir: cat.name,
        });
        continue;
      }
      out.push({
        ...parsed.data,
        _body: parsed.body,
        dir: rel(dir),
        file: rel(file),
        slugDir: slug.name,
        catDir: cat.name,
        assets: listAssets(dir),
      });
    }
  }

  out.sort((a, b) => (a.catDir + '/' + a.slugDir).localeCompare(b.catDir + '/' + b.slugDir));
  return out;
}

function listAssets(dir) {
  const res = { code: [], evidence: [], assets: [] };
  for (const k of Object.keys(res)) {
    const d = join(dir, k);
    if (existsSync(d) && statSync(d).isDirectory()) {
      res[k] = walkRel(d, d);
    }
  }
  return res;
}

function walkRel(dir, base, out = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, e.name);
    if (e.isDirectory()) walkRel(full, base, out);
    else out.push(relative(base, full).split(sep).join('/'));
  }
  return out;
}

function rel(p) {
  return relative(ROOT, p).split(sep).join('/');
}

/** The canonical public path for an idea. Stable forever — see SEO notes in CONTRIBUTING.md. */
export function ideaPath(idea) {
  return `/ideas/${idea.category ?? idea.catDir}/${idea.id ?? idea.slugDir}/`;
}

export const GENERATED_BANNER =
  '<!-- GENERATED by scripts/build.mjs — do not edit by hand. Run `npm run build`. -->';
