#!/usr/bin/env node
/**
 * build.mjs — generates every navigable surface from idea.md frontmatter.
 *
 * Adding an idea = drop a folder + run this. There is no index to remember to touch,
 * so nothing rots. Every output carries a GENERATED banner and CI fails on hand-edits.
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { ROOT, loadIdeas, loadTaxonomy, loadSources, ideaPath, readJSON as readJSONFile, GENERATED_BANNER } from './lib/ideas.mjs';

// Where things actually live. `site` is null until a site is really deployed — see
// data/site.json. Until then every generated URL points at the repo, which resolves.
const siteCfg = readJSONFile('data/site.json');
const SITE = siteCfg.site;                 // null when there is no website yet
const REPO = siteCfg.repo;
const HAS_SITE = typeof SITE === 'string' && SITE.startsWith('https://');
const BLOB = `${REPO}/blob/main`;
const TREE = `${REPO}/tree/main`;

// Canonical URL for an idea: the site when one exists, otherwise the file on GitHub.
const ideaUrl = (i) => (HAS_SITE ? SITE + ideaPath(i) : `${TREE}/ideas/${i.category}/${i.id}`);
const docUrl = (f) => (HAS_SITE ? `${SITE}/${f}` : `${BLOB}/${f}`);
const catUrl = (c) => (HAS_SITE ? `${SITE}/ideas/${c}/` : `${TREE}/ideas/${c}`);

const tax = loadTaxonomy();
const sources = loadSources();
const ideas = loadIdeas().filter((i) => !i._error);

const write = (rel, content) => {
  const p = join(ROOT, rel);
  mkdirSync(dirname(p), { recursive: true });
  const next = content.endsWith('\n') ? content : content + '\n';
  const prev = existsSync(p) ? readFileSync(p, 'utf8') : null;
  if (prev !== next) writeFileSync(p, next, 'utf8');
  return rel;
};

// Deliberately NOT git-derived. An earlier version read each idea's last commit
// date, which made build-idempotent structurally unsatisfiable: the commit date of
// a file you are about to commit is unknowable, so the first build after adding an
// idea always differed from the build CI produced afterwards. Every generated field
// is now a pure function of repository CONTENT, which is what recomputable has to
// mean to be worth anything.
const ideaDate = (i) => {
  const d = i.ended || i.started || null;
  if (!d) return null;
  const parts = String(d).split('-');
  const [y, m, day] = [parts[0], parts[1] || '01', parts[2] || '01'];
  return `${y}-${m}-${day}T00:00:00Z`;
};

const OUTCOME_ICON = {
  revenue: '💰', shipped: '🚢', partial: '◐', failed: '✖',
  abandoned: '⏹', inconclusive: '?', active: '▶', parked: '⏸',
};

const NL = String.fromCharCode(10);
const byOutcome = (o) => ideas.filter((i) => i.outcome === o);
const anchor = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');

// ---------------------------------------------------------------------------
// index.json — the whole catalog in one fetch. The agent entry point.
// ---------------------------------------------------------------------------
const catalog = ideas.map((i) => ({
  id: i.id,
  title: i.title,
  description: i.description,
  category: i.category,
  outcome: i.outcome,
  verdict: i.verdict,
  what_would_settle_it: i.what_would_settle_it ?? null,
  confidence: i.confidence,
  started: i.started ?? null,
  ended: i.ended ?? null,
  effort: i.effort,
  cost_usd: i.cost_usd ?? null,
  revenue_usd: i.revenue_usd ?? null,
  stack: i.stack ?? [],
  tags: i.tags ?? [],
  tags_by_axis: Object.fromEntries(
    ['domain', 'mechanic', 'stage'].map((ax) => [ax, (i.tags ?? []).filter((t) => tax.tagDefs.get(t)?.axis === ax)])
  ),
  lessons: i.lessons ?? [],
  reusable: i.reusable ?? [],
  evidence: i.evidence ?? [],
  related: i.related ?? [],
  supersedes: i.supersedes ?? [],
  source: i.source,
  links: i.links ?? {},
  path: ideaPath(i),
  url: ideaUrl(i),
  repo_path: i.dir,
  updated: ideaDate(i),
}));

// back-links: `related` is symmetric in the generated data even when written one way
const backlinks = new Map();
for (const c of catalog) for (const r of c.related) {
  if (!backlinks.has(r)) backlinks.set(r, new Set());
  backlinks.get(r).add(c.id);
}
for (const c of catalog) {
  c.related_all = [...new Set([...c.related, ...(backlinks.get(c.id) ?? [])])].sort();
}

const counts = {
  total: ideas.length,
  by_outcome: Object.fromEntries(tax.raw.outcomes.map((o) => [o.id, byOutcome(o.id).length])),
  by_category: Object.fromEntries(tax.categories.map((c) => [c.id, ideas.filter((i) => i.category === c.id).length])),
  by_source: Object.fromEntries(sources.digs.map((d) => [d.id, ideas.filter((i) => i.source === d.id).length])),
  lessons: ideas.reduce((n, i) => n + (i.lessons?.length ?? 0), 0),
  open_questions: byOutcome('inconclusive').length,
};

write('index.json', JSON.stringify({
  generated_note: 'GENERATED by scripts/build.mjs — do not edit. Source of truth is each ideas/**/idea.md.',
  site: SITE,
  repo: REPO,
  canonical: HAS_SITE ? 'site' : 'repo',
  license: { prose: 'CC-BY-4.0', code: 'MIT', attribution: siteCfg.attribution },
  counts,
  taxonomy: {
    categories: tax.categories,
    outcomes: tax.raw.outcomes,
    tags: tax.raw.tags,
  },
  digs: sources.digs.map((d) => ({ ...d, yield: counts.by_source[d.id] ?? 0 })),
  ideas: catalog,
}, null, 2));

// ---------------------------------------------------------------------------
// llms.txt + llms-full.txt
// ---------------------------------------------------------------------------
const llms = [
  '# idea-library',
  '',
  '> A public record of ideas we actually ran, each with an outcome and the reason behind it.',
  '> Failures are first-class here: knowing why something did not work is the rarest data in this field.',
  '',
  `Ideas: ${counts.total} · lessons: ${counts.lessons} · open questions: ${counts.open_questions}`,
  '',
  '## Start here',
  '',
  `- [index.json](${docUrl('index.json')}): the entire catalog in one fetch. Read this first; do not crawl the tree.`,
  `- [llms-full.txt](${docUrl('llms-full.txt')}): every idea inlined, for single-shot ingestion.`,
  `- [AGENTS.md](${docUrl('AGENTS.md')}): how to contribute. Applies to every agent, any vendor.`,
  `- [LESSONS.md](${docUrl('LESSONS.md')}): every lesson in the library, grouped by failure mechanic.`,
  `- [FAILURES.md](${docUrl('FAILURES.md')}): what did not work, and why.`,
  `- [OPEN-QUESTIONS.md](${docUrl('OPEN-QUESTIONS.md')}): verdicts we cannot call yet, with the measurement that would settle each.`,
  `- [STATUS.md](${docUrl('STATUS.md')}): which parts of our history have been excavated, and which have not.`,
  '',
  '## Categories',
  '',
  ...tax.categories
    .filter((c) => counts.by_category[c.id] > 0)
    .map((c) => `- [${c.label}](${catUrl(c.id)}) (${counts.by_category[c.id]}): ${c.definition}`),
  '',
  '## Ideas',
  '',
  ...catalog.map((c) => `- [${c.title}](${c.url}) — \`${c.outcome}\`: ${c.description}`),
  '',
  '## Citation',
  '',
  `Prose CC-BY-4.0, code MIT. Cite as: ${siteCfg.attribution}, <idea title>, ${HAS_SITE ? SITE : REPO}`,
  '',
].join('\n');
write('llms.txt', llms);

write('llms-full.txt', [
  llms,
  '',
  '---',
  '',
  '# Full corpus',
  '',
  ...catalog.map((c) => {
    const src = ideas.find((i) => i.id === c.id);
    return [
      `## ${c.title}`,
      '',
      `- id: ${c.id}`,
      `- url: ${c.url}`,
      `- category: ${c.category}`,
      `- outcome: ${c.outcome} (confidence: ${c.confidence})`,
      `- verdict: ${c.verdict}`,
      c.what_would_settle_it ? `- what would settle it: ${c.what_would_settle_it}` : null,
      `- effort: ${c.effort}${c.cost_usd != null ? ` · cost: $${c.cost_usd}` : ''}${c.revenue_usd != null ? ` · revenue: $${c.revenue_usd}` : ''}`,
      `- tags: ${c.tags.join(', ')}`,
      '',
      '### Lessons',
      ...c.lessons.map((l) => `- ${l}`),
      '',
      (src?._body ?? '').trim(),
      '',
    ].filter((x) => x !== null).join('\n');
  }),
].join('\n'));

// ---------------------------------------------------------------------------
// LESSONS.md — grouped by mechanic. The highest-value page in the repo.
// ---------------------------------------------------------------------------
{
  const lines = [
    GENERATED_BANNER, '',
    '# Lessons',
    '',
    `Every lesson in the library — ${counts.lessons} of them — grouped by the mechanic that produced it.`,
    'Each line is written to survive being quoted on its own, and each has a stable anchor so a',
    'citation lands on the exact claim.',
    '',
  ];
  for (const mech of tax.raw.tags.mechanic) {
    const hits = ideas.filter((i) => (i.tags ?? []).includes(mech.id) && (i.lessons ?? []).length);
    if (!hits.length) continue;
    lines.push(`## ${mech.id}`, '', `*${mech.definition}*`, '');
    for (const i of hits) {
      for (const [n, l] of (i.lessons ?? []).entries()) {
        lines.push(`- <a id="${anchor(i.id)}-${n + 1}"></a>${l} — [${i.title}](${ideaPath(i)}) \`${i.outcome}\``);
      }
    }
    lines.push('');
  }
  const untagged = ideas.filter((i) => !(i.tags ?? []).some((t) => tax.tagDefs.get(t)?.axis === 'mechanic'));
  if (untagged.length) lines.push(`> ${untagged.length} idea(s) carry no mechanic tag and are missing from this page.`, '');
  write('LESSONS.md', lines.join('\n'));
}

// ---------------------------------------------------------------------------
// FAILURES.md / WORKED.md / OPEN-QUESTIONS.md
// ---------------------------------------------------------------------------
const EFFORT_RANK = { months: 4, weeks: 3, days: 2, hours: 1 };
const table = (rows) => [
  '| Idea | Outcome | Effort | Cost | Why |',
  '|---|---|---|---|---|',
  ...rows.map((i) => `| [${esc(i.title)}](${ideaPath(i)}) | \`${i.outcome}\` | ${i.effort} | ${i.cost_usd != null ? '$' + i.cost_usd : '—'} | ${esc(i.verdict)} |`),
].join('\n');

{
  const rows = ideas.filter((i) => ['failed', 'abandoned', 'partial'].includes(i.outcome))
    .sort((a, b) => (EFFORT_RANK[b.effort] ?? 0) - (EFFORT_RANK[a.effort] ?? 0));
  write('FAILURES.md', [
    GENERATED_BANNER, '',
    '# What did not work',
    '',
    'Sorted by effort burned, heaviest first — the expensive failures are the ones worth reading.',
    'A failure with a known cause is a finished experiment, not a wasted one.',
    '',
    rows.length ? table(rows) : '_Nothing here yet._',
    '',
  ].join('\n'));
}

{
  const rows = ideas.filter((i) => ['revenue', 'shipped'].includes(i.outcome))
    .sort((a, b) => (b.revenue_usd ?? 0) - (a.revenue_usd ?? 0));
  write('WORKED.md', [
    GENERATED_BANNER, '',
    '# What worked',
    '',
    'Shipped or earning. The `mechanic` tags say what carried each one — that is the transferable part.',
    '',
    rows.length ? table(rows) : '_Nothing here yet._',
    '',
  ].join('\n'));
}

{
  const rows = ideas.filter((i) => i.outcome === 'inconclusive');
  write('OPEN-QUESTIONS.md', [
    GENERATED_BANNER, '',
    '# Open questions',
    '',
    'Verdicts we cannot call yet. Each names the measurement that would settle it.',
    'If you have spare compute and want to contribute something genuinely useful, start here:',
    'settling one of these is worth more to the library than a new idea.',
    '',
    ...(rows.length ? rows.flatMap((i) => [
      `### [${i.title}](${ideaPath(i)})`,
      '',
      `${i.description}`,
      '',
      `**What would settle it:** ${i.what_would_settle_it}`,
      '',
    ]) : ['_Nothing open right now._', '']),
  ].join('\n'));
}

// ---------------------------------------------------------------------------
// STATUS.md — the digs board. Keeps the library honest about being incomplete.
// ---------------------------------------------------------------------------
{
  const rows = sources.digs.map((d) => {
    const y = counts.by_source[d.id] ?? 0;
    const status = d.status === 'complete' ? '✅ complete' : d.status === 'open' ? '♾ open' : '⏳ pending';
    return `| ${d.label} | ${status} | ${y} | ${d.estimated ? '~' + d.estimated : '—'} | ${d.detail} |`;
  });
  const pending = sources.digs.filter((d) => d.status === 'pending');
  write('STATUS.md', [
    GENERATED_BANNER, '',
    '# Excavation status',
    '',
    'This library is built by repeated digs through our own history. The registry we started from',
    'was the easiest one, and it is nowhere near all of it. This board exists so the gaps stay',
    'visible instead of being quietly forgotten.',
    '',
    `**${counts.total} ideas indexed · ${pending.length} digs still outstanding.**`,
    '',
    '| Dig | Status | Yielded | Estimated | Notes |',
    '|---|---|---|---|---|',
    ...rows,
    '',
    '## By outcome',
    '',
    '| Outcome | Count | Meaning |',
    '|---|---|---|',
    ...tax.raw.outcomes.map((o) => `| ${OUTCOME_ICON[o.id] ?? ''} \`${o.id}\` | ${counts.by_outcome[o.id]} | ${o.definition} |`),
    '',
  ].join('\n'));
}

// ---------------------------------------------------------------------------
// Per-category READMEs
// ---------------------------------------------------------------------------
for (const cat of tax.categories) {
  const rows = ideas.filter((i) => i.category === cat.id);
  if (!rows.length) continue;
  write(`ideas/${cat.id}/README.md`, [
    GENERATED_BANNER, '',
    `# ${cat.label}`,
    '',
    cat.definition,
    '',
    `${rows.length} idea(s).`,
    '',
    table(rows),
    '',
    `[← all categories](${REPO}#categories)`,
    '',
  ].join('\n'));
}

// ---------------------------------------------------------------------------
// README.md — generated between markers so the hero stays hand-written.
// ---------------------------------------------------------------------------
{
  const block = [
    '<!-- BUILD:START -->',
    GENERATED_BANNER,
    '',
    `**${counts.total} ideas · ${counts.lessons} lessons · ${counts.open_questions} open question${counts.open_questions === 1 ? '' : 's'} · ${sources.digs.filter((d) => d.status === 'pending').length} digs outstanding**`,
    '',
    '| Outcome | Count |',
    '|---|---|',
    ...tax.raw.outcomes.filter((o) => counts.by_outcome[o.id] > 0)
      .map((o) => `| ${OUTCOME_ICON[o.id] ?? ''} \`${o.id}\` — ${o.definition} | ${counts.by_outcome[o.id]} |`),
    '',
    '### Categories',
    '',
    '| Category | Ideas | What is in it |',
    '|---|---|---|',
    ...tax.categories.filter((c) => counts.by_category[c.id] > 0)
      .map((c) => `| [${c.label}](ideas/${c.id}/) | ${counts.by_category[c.id]} | ${c.definition} |`),
    '',
    '<!-- BUILD:END -->',
  ].join('\n');

  const readmePath = join(ROOT, 'README.md');
  if (existsSync(readmePath)) {
    const cur = readFileSync(readmePath, 'utf8');
    const next = cur.replace(/<!-- BUILD:START -->[\s\S]*?<!-- BUILD:END -->/, block);
    write('README.md', next);
  }
}

// ---------------------------------------------------------------------------
// sitemap.xml / robots.txt / feed.xml — ONLY when a site actually exists.
// Generating crawler files for a domain that does not resolve is worse than not
// having them: it publishes broken canonical URLs as if they were real.
// ---------------------------------------------------------------------------
if (HAS_SITE) {
  write('sitemap.xml', [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    `  <url><loc>${SITE}/</loc></url>`,
    ...tax.categories.filter((c) => counts.by_category[c.id] > 0)
      .map((c) => `  <url><loc>${SITE}/ideas/${c.id}/</loc></url>`),
    ...catalog.map((c) =>
      `  <url><loc>${c.url}</loc>${c.updated ? `<lastmod>${c.updated}</lastmod>` : ''}</url>`),
    '</urlset>',
  ].join(NL));

  write('robots.txt', [
    '# Every crawler and every answer engine is welcome here. That is the point.',
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${SITE}/sitemap.xml`,
    '',
    '# Machine-readable entry points:',
    `#   ${SITE}/index.json      full catalog, one fetch`,
    `#   ${SITE}/llms.txt        map`,
    `#   ${SITE}/llms-full.txt   entire corpus inline`,
  ].join(NL));

  const rfc822 = (iso) => (iso ? new Date(iso).toUTCString() : new Date().toUTCString());
  write('feed.xml', [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0"><channel>',
    '  <title>idea-library</title>',
    `  <link>${SITE}/</link>`,
    '  <description>Ideas we ran, and what actually happened.</description>',
    ...[...catalog].sort((a, b) => String(b.updated ?? '').localeCompare(String(a.updated ?? ''))).slice(0, 50)
      .map((c) => [
        '  <item>',
        `    <title>${escXml(c.title)}</title>`,
        `    <link>${c.url}</link>`,
        `    <guid>${c.url}</guid>`,
        `    <pubDate>${rfc822(c.updated)}</pubDate>`,
        `    <description>${escXml(c.description)} (${c.outcome})</description>`,
        '  </item>',
      ].join(NL)),
    '</channel></rss>',
  ].join(NL));
}

function escXml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

console.log(`build: ${ideas.length} ideas · ${counts.lessons} lessons · canonical URLs point at the ${HAS_SITE ? 'site' : 'repo'}`);
if (!HAS_SITE) console.log('build: no site configured (data/site.json), so sitemap.xml / robots.txt / feed.xml were not generated.');
