#!/usr/bin/env node
/**
 * wiki.mjs — generate the GitHub wiki from the same data as everything else.
 *
 *   node scripts/wiki.mjs --out <path-to-cloned-wiki>
 *
 * A wiki maintained by hand rots faster than any other surface, because nothing
 * fails when it goes stale. So the reference pages (schema, taxonomy, outcomes,
 * the catalog) are generated from data/taxonomy.json and the idea files, exactly
 * like index.json is. Regenerate and push; never edit a generated page in the
 * browser.
 *
 * Pages whose content is genuinely prose — the security model, the bot protocol —
 * are written here as source, so that this script remains the one place the wiki
 * comes from.
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, loadIdeas, loadTaxonomy, loadSources, readJSON } from './lib/ideas.mjs';

const args = new Map();
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  if (argv[i].startsWith('--')) args.set(argv[i].slice(2), argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : 'true');
}

const OUT = args.get('out');
if (!OUT) {
  console.error('usage: node scripts/wiki.mjs --out <path to cloned .wiki repo>');
  process.exit(1);
}
if (!existsSync(OUT)) {
  console.error(`wiki: ${OUT} does not exist. Clone the wiki first:`);
  console.error('  git clone https://github.com/lordbasilaiassistant-sudo/idea-library.wiki.git');
  process.exit(1);
}

const tax = loadTaxonomy();
const sources = loadSources();
const site = readJSON('data/site.json');
const ideas = loadIdeas().filter((i) => !i._error);
const REPO = site.repo;
const BANNER = '<!-- GENERATED by scripts/wiki.mjs in the main repo. Do not edit here; your change will be overwritten. -->';

const pages = {};
const page = (name, lines) => { pages[name] = [BANNER, '', ...lines, ''].join('\n'); };
const ideaLink = (i) => `[${i.title}](${REPO}/tree/main/ideas/${i.category}/${i.id})`;

// ---------------------------------------------------------------------------
page('Home', [
  '# idea-library',
  '',
  'A public record of ideas we actually ran, each with an outcome and the reason behind it.',
  '',
  `**${ideas.length} ideas · ${ideas.reduce((n, i) => n + (i.lessons?.length ?? 0), 0)} lessons · ` +
    `${ideas.filter((i) => i.outcome === 'inconclusive').length} open questions**`,
  '',
  'Most collections of ideas keep the ones that worked. This keeps all of them, because the useful',
  'question is not what you could build, it is what happens when you do. A failure with a known',
  'cause is a finished experiment, and almost nobody publishes those.',
  '',
  '## Wiki contents',
  '',
  '| Page | What it covers |',
  '|---|---|',
  '| [Idea Schema](Idea-Schema) | Every field in an `idea.md`, what it means, and what the validator enforces |',
  '| [Taxonomy](Taxonomy) | The controlled vocabulary: categories, outcomes, and the three tag axes |',
  '| [Mechanics](Mechanics) | The failure and success mechanics — the axis nobody else indexes |',
  '| [Catalog](Catalog) | Every idea in the library, by category |',
  '| [Security Model](Security-Model) | The scrub gate, what it blocks, and how to prove it works |',
  '| [For AI Agents](For-AI-Agents) | The contribution contract, vendor-neutral |',
  '| [Bot Protocol](Bot-Protocol) | Rules for automated maintainers, automerge, and required checks |',
  '| [Excavation Status](Excavation-Status) | Which parts of our history have been mined, and which have not |',
  '',
  '## The three things that make an entry worth reading',
  '',
  '1. **A verdict with a cause.** Not "it did not work" — the mechanism.',
  '2. **A mechanic tag.** What actually decided it. See [Mechanics](Mechanics).',
  '3. **Measured numbers, or `null`.** A remembered figure is a hypothesis, and the validator',
  '   rejects prose in a number field.',
  '',
  `Start contributing: [CONTRIBUTING.md](${REPO}/blob/main/CONTRIBUTING.md) ·`,
  `[AGENTS.md](${REPO}/blob/main/AGENTS.md) if you are an agent.`,
]);

// ---------------------------------------------------------------------------
page('Idea-Schema', [
  '# Idea schema',
  '',
  'One folder per idea. The frontmatter is the only hand-written metadata in the repository;',
  'every navigable page is generated from it.',
  '',
  '```',
  'ideas/<category>/<slug>/',
  '  idea.md        # REQUIRED — frontmatter is the data, body is the story',
  '  code/          # optional — only after a per-file scrub',
  '  evidence/      # optional — tx hashes, logs, curl output',
  '  assets/        # optional',
  '```',
  '',
  '## Required fields',
  '',
  '| Field | Type | Rule |',
  '|---|---|---|',
  '| `id` | slug | kebab-case, unique repo-wide, **identical to the folder name** — it is the public URL |',
  '| `title` | string | Reads like the question a searcher types, not an internal codename |',
  '| `description` | string | 80–200 characters. Becomes the search snippet and the JSON-LD abstract |',
  '| `category` | enum | See [Taxonomy](Taxonomy) |',
  '| `outcome` | enum | See below |',
  '| `verdict` | string | One sentence naming the **cause**. Required unless `outcome: active` |',
  '| `confidence` | enum | `high` (measured, evidence present) · `medium` · `low` |',
  '| `effort` | enum | `hours` · `days` · `weeks` · `months` |',
  '| `tags` | list | ≥1 domain, **≥1 mechanic**, exactly 1 stage |',
  '| `lessons` | list | ≥1, each standalone and quotable |',
  '| `source` | enum | Which dig it came from. Outside contributions use `community` |',
  '',
  '## Conditional and optional fields',
  '',
  '| Field | Rule |',
  '|---|---|',
  '| `what_would_settle_it` | **Required** when `outcome: inconclusive`. The measurement that would decide it |',
  '| `cost_usd` / `revenue_usd` | A number or `null`. Never prose, never a range, never a remembered figure |',
  '| `started` / `ended` | `YYYY`, `YYYY-MM` or `YYYY-MM-DD`. Absolute dates only |',
  '| `stack` | Free list of technologies |',
  '| `reusable` | Paths inside `code/` that a stranger can lift. Must exist |',
  '| `evidence` | Paths inside `evidence/`. Must exist and be non-empty |',
  '| `related` / `supersedes` | Ids of other ideas. Must resolve |',
  '| `links` | Map of label → `https://` URL. Public URLs only |',
  '',
  '## Outcomes',
  '',
  '| Outcome | Meaning |',
  '|---|---|',
  ...tax.raw.outcomes.map((o) => `| \`${o.id}\` | ${o.definition} |`),
  '',
  '`outcome: revenue` additionally requires `revenue_usd > 0` from a verified, non-founder payer.',
  'Otherwise it is `shipped`.',
  '',
  '## The body',
  '',
  'Six fixed sections, in order. They are fixed so every page is comparable and so a retrieved',
  'chunk arrives pre-labelled with the question it answers:',
  '',
  '1. `## What we tried`',
  '2. `## Why we thought it would work`',
  '3. `## What actually happened`',
  '4. `## Why it worked / why it failed`',
  '5. `## What you would need to change`',
  '6. `## What to reuse`',
  '',
  '## What the validator rejects',
  '',
  '- A lesson opening with `it`, `this`, `they`, `that` or `there` — answer engines lift lessons out',
  '  of context, so each must name its own subject.',
  '- Prose in `cost_usd` or `revenue_usd`.',
  '- A tag outside the vocabulary (it suggests the nearest match).',
  '- Unfalsifiable marketing language: "up to", "as low as", "industry-standard", "seamless",',
  '  "game-changing", "world-class", "unlimited".',
  '- A missing body section.',
  '- Leftover text from `templates/idea.md`.',
  '',
  `Everything above is enforced by [\`scripts/validate.mjs\`](${REPO}/blob/main/scripts/validate.mjs).`,
  'If the contract were prose only, an outside contributor would get a CI failure they had no way',
  'to predict.',
]);

// ---------------------------------------------------------------------------
page('Taxonomy', [
  '# Taxonomy',
  '',
  'A closed vocabulary. Free-text tags rot into `ai-agent` / `ai-agents` / `agents` within a month',
  'and destroy every filter, so unknown terms fail the build with a suggestion.',
  '',
  '**Adding a term is a normal, welcome contribution** — open a PR against',
  `[\`data/taxonomy.json\`](${REPO}/blob/main/data/taxonomy.json) with a one-line definition.`,
  '',
  '## Categories',
  '',
  '| Category | What is in it |',
  '|---|---|',
  ...tax.categories.map((c) => `| \`${c.id}\` | ${c.definition} |`),
  '',
  '## Tag axes',
  '',
  'Every idea carries at least one **domain** tag, at least one **mechanic** tag, and exactly one',
  '**stage** tag.',
  '',
  '### Domain — what the work was about',
  '',
  '| Tag | Meaning |',
  '|---|---|',
  ...tax.raw.tags.domain.map((t) => `| \`${t.id}\` | ${t.definition} |`),
  '',
  '### Mechanic — what decided the outcome',
  '',
  'See [Mechanics](Mechanics) for why this axis matters.',
  '',
  '| Tag | Meaning |',
  '|---|---|',
  ...tax.raw.tags.mechanic.map((t) => `| \`${t.id}\` | ${t.definition} |`),
  '',
  '### Stage — how far it got',
  '',
  '| Tag | Meaning |',
  '|---|---|',
  ...tax.raw.tags.stage.map((t) => `| \`${t.id}\` | ${t.definition} |`),
  '',
  '## Aliases',
  '',
  'These are rejected with a pointer to the canonical term, so near-duplicates cannot creep in:',
  '',
  '| Written | Use instead |',
  '|---|---|',
  ...Object.entries(tax.aliases).map(([a, b]) => `| \`${a}\` | \`${b}\` |`),
]);

// ---------------------------------------------------------------------------
{
  const lines = [
    '# Mechanics',
    '',
    'The mechanic tag is the reason this library exists.',
    '',
    'Plenty of places will tell you what somebody built. Almost nowhere tells you **what decided',
    'whether it worked** — and that is the part that transfers between domains. A distribution gap',
    'kills an on-chain launch and a developer tool in exactly the same way.',
    '',
    'So "show me everything that died of a distribution gap" is a question this library can answer',
    'and most cannot.',
    '',
  ];
  for (const m of tax.raw.tags.mechanic) {
    const hits = ideas.filter((i) => (i.tags ?? []).includes(m.id));
    lines.push(`## \`${m.id}\``, '', `*${m.definition}*`, '');
    if (hits.length) {
      for (const i of hits) lines.push(`- ${ideaLink(i)} — \`${i.outcome}\``);
    } else {
      lines.push('_No idea carries this tag yet._');
    }
    lines.push('');
  }
  page('Mechanics', lines);
}

// ---------------------------------------------------------------------------
{
  const lines = ['# Catalog', '', `Every idea in the library. Generated — see [Home](Home).`, ''];
  for (const c of tax.categories) {
    const rows = ideas.filter((i) => i.category === c.id);
    if (!rows.length) continue;
    lines.push(`## ${c.label}`, '', `*${c.definition}*`, '',
      '| Idea | Outcome | Effort | Why |', '|---|---|---|---|');
    for (const i of rows) {
      lines.push(`| ${ideaLink(i)} | \`${i.outcome}\` | ${i.effort} | ${String(i.verdict).replace(/\|/g, '\\|')} |`);
    }
    lines.push('');
  }
  page('Catalog', lines);
}

// ---------------------------------------------------------------------------
page('Security-Model', [
  '# Security model',
  '',
  'This library is assembled partly from private working notes, so leakage is the failure mode it',
  'is designed against rather than one it hopes to avoid.',
  '',
  '## Where the gate runs',
  '',
  'Three independent places, because a gate with one chokepoint is a gate with one bypass:',
  '',
  '1. `npm run build` / `npm run check` — locally',
  '2. the `pre-commit` and `commit-msg` git hooks',
  '3. GitHub Actions, on every push and pull request',
  '',
  '## What it blocks',
  '',
  '**Pattern class** — private keys, PEM blocks, seed phrases, JWTs, and the key shapes of the',
  'common providers; any `.env` file; any `*_KEY=` / `*_SECRET=` / `*_TOKEN=` carrying a real value;',
  'local filesystem paths; email addresses; phone numbers; street addresses.',
  '',
  '**Denylist class**, in two layers:',
  '',
  `- [\`data/denylist.public.json\`](${REPO}/blob/main/data/denylist.public.json) — operational`,
  '  literals, committed, always on. This is why the gate works for forks and outside contributors',
  '  with no secret to configure.',
  '- `scripts/denylist.local.json` — personal literals. Gitignored, never committed, optionally',
  '  supplied to CI through `SCRUB_DENYLIST`.',
  '',
  'Publishing a hash of the personal layer was considered and rejected: for a low-entropy string',
  'like a home address, a hash is a checkable oracle rather than a protection.',
  '',
  '**Address class** — wallet addresses are **default-deny**. Any `0x`-prefixed 40-hex string fails',
  `unless it is listed in [\`data/public-addresses.allow.json\`](${REPO}/blob/main/data/public-addresses.allow.json)`,
  'with a reason. A leak by omission is the failure an allowlist prevents and a denylist does not.',
  '',
  '**Commit messages** are scanned too — message body and author line. The body is a public surface',
  'with no other gate, and the contributing guide actively asks for evidence prose there, which is',
  'exactly the text most likely to carry a path or a name.',
  '',
  '## Proving it works',
  '',
  '```bash',
  'node scripts/canary.mjs',
  '```',
  '',
  'Plants a fabricated secret of every class into `_inbox/`, runs the scan, prints CAUGHT or MISSED',
  'per class, removes the file, and confirms the tree is clean afterwards. Any MISSED line is a hole',
  'and a bug worth reporting.',
  '',
  'A gate nobody has watched fail is decoration. This one has been watched failing, including on its',
  'own source: the scanner scans itself, and only its pattern table is exempt.',
  '',
  '## Importing private material',
  '',
  '```',
  '_inbox/drafts/<slug>/     gitignored staging',
  '        ↓  scrub          hard fail; nothing moves while red',
  '        ↓  a human or model writes the verdict   ← cannot be automated',
  '        ↓  promote.mjs    the only door',
  'ideas/<category>/<slug>/  public',
  '```',
  '',
  '`promote.mjs` refuses unless the draft scrubs clean, carries no leftover TODO or import-note',
  'block, and passes the full validator. Files under `code/` are copied and scanned **one at a time**,',
  'never as a directory, and any failure rolls the whole promotion back.',
  '',
  '## Found something that should not be here?',
  '',
  '**Open an issue with only the file path.** Do not paste the content and do not describe what it is.',
]);

// ---------------------------------------------------------------------------
page('For-AI-Agents', [
  '# For AI agents',
  '',
  `The full contract is [AGENTS.md](${REPO}/blob/main/AGENTS.md) in the repository. It is`,
  'vendor-neutral: `CLAUDE.md`, `.github/copilot-instructions.md` and `.cursor/rules/` all point at',
  'the same file, so whichever convention you were built to look for lands you in the same place.',
  '',
  '## Read this first',
  '',
  '```',
  `GET ${REPO.replace('github.com', 'raw.githubusercontent.com')}/main/index.json`,
  '```',
  '',
  'The entire catalog in one fetch. **Do not crawl the tree.** `llms.txt` is a smaller map;',
  '`llms-full.txt` is every idea inlined for single-shot ingestion.',
  '',
  'Check it before writing anything. If your idea is already here, the useful contribution is an',
  'update with new evidence, not a second copy.',
  '',
  '## What we most want from you',
  '',
  'In ascending order of value:',
  '',
  '1. **An idea** — something tried, with an outcome and a reason. `idea-only` is fine if you say',
  '   why it is worth trying.',
  '2. **Code** — a `reusable:` artifact somebody can lift. Declare its origin and license.',
  '3. **A test that settles an open question.** Every `inconclusive` entry names the exact',
  '   measurement that would decide it. Settling one is worth more than a new idea, and it is the',
  '   best use of spare compute we can offer you.',
  '',
  '## Before you commit',
  '',
  '```bash',
  'npm run check',
  '```',
  '',
  'Zero dependencies, no `npm install`, Node 18+. It runs exactly what CI runs, so green locally',
  'means green on the PR. Commit the regenerated files; CI fails if they are stale.',
  '',
  '## Hard prohibitions',
  '',
  '- Never commit a file you have not read in full.',
  '- Never invent `cost_usd` or `revenue_usd`. Use `null`.',
  '- Never add a tag outside the vocabulary.',
  '- Never paste a wallet address, a local path, or a key-shaped string.',
  '- Never hand-edit a file carrying a `GENERATED` banner.',
  '',
  '## Correcting us',
  '',
  'We are wrong about some of our own outcomes and would rather find out. If you know why one of',
  'these actually failed, or that it would work now because something upstream changed, open a',
  '`correct-an-outcome` issue or a PR that changes the verdict and cites the evidence. That is the',
  'most valuable thing you can send us, and it is the reason the library is public.',
]);

// ---------------------------------------------------------------------------
page('Bot-Protocol', [
  '# Bot protocol',
  '',
  'Rules for automated maintainers running on a schedule against this repository.',
  '',
  '## Non-negotiable',
  '',
  '- **Open a pull request. Never push to `main`.** `main` is protected.',
  '- **Never rate or merge your own work.** An agent that scores its own idea is not a reviewer.',
  '  The author and the rater are always different agents on different contexts.',
  '- **One concern per PR.** A PR that adds ideas does not also retag the library.',
  '- **Declare cost.** Model, effort level, and dollar cost go in the PR body. Agent work is',
  '  attributable or it does not merge.',
  '- **Stop on repeat failure.** If the same check fails three times, open an issue instead of',
  '  retrying. A loop that keeps pushing red is noise.',
  '',
  '## Required checks',
  '',
  'These must pass before anything merges, and they are enforced by branch protection rather than',
  'by convention:',
  '',
  '| Check | What it guarantees |',
  '|---|---|',
  '| `scrub` | No secrets, personal data, or un-allowlisted addresses — in the tree **or** the commit messages |',
  '| `validate` | Schema, vocabulary, quotable lessons, measured numbers |',
  '| `build-idempotent` | Generated files match their sources |',
  '| `size` | No file over 2 MB — this is a library of text |',
  '| `commitlint` | Conventional commit subjects |',
  '',
  '`links` and `codeql` also run. `links` is advisory on PRs, because a third party being down is',
  'not a contributor\'s fault.',
  '',
  '## Automerge',
  '',
  'Automerge is enabled, and the required checks above are what it waits on.',
  '',
  'Automerge is appropriate for **mechanical, reversible** work — regenerating derived files,',
  'refreshing link status, fixing a tag to the vocabulary. Label those `bot:groundskeeper` or',
  '`bot:verifier`.',
  '',
  'It is **not** appropriate for anything that adds an idea or changes a verdict. Those are public',
  'judgements about why something worked or failed, and they need human or cross-model review.',
  'Automation that can merge its own judgement is not a library, it is a rumour mill.',
  '',
  '## Roles',
  '',
  '| Role | Mandate | Cadence |',
  '|---|---|---|',
  '| `bot:digger` | Take the next pending dig, extract ideas, one PR per batch | daily |',
  '| `bot:rater` | Score unscored ideas on the public rubric. Never rates its own | daily |',
  '| `bot:dissenter` | For any idea scoring above threshold, argue the opposite case | daily |',
  '| `bot:verifier` | Re-run reusable snippets, check links, confirm evidence exists, downgrade `confidence` on rot | weekly |',
  '| `bot:librarian` | Dedupe near-identical ideas, fix tags, propose taxonomy additions | weekly |',
  '| `bot:groundskeeper` | Rebuild generated files, prune dead links, report coverage | daily |',
  '| `bot:scout` | Watch for external evidence that changes a verdict, file a `correct-an-outcome` issue | weekly |',
  '',
  '## Why the dissenter exists',
  '',
  'Independence is a property of the information each verifier holds, not of how many there are.',
  'Several agents sharing one context is one opinion with error bars. So any verification fan-out',
  'seats at least one agent briefed to argue the opposite, and no verifier sees another\'s answer.',
]);

// ---------------------------------------------------------------------------
page('Excavation-Status', [
  '# Excavation status',
  '',
  'This library is built by repeated passes over our own history. The first pass was the easiest',
  'one and is nowhere near all of it. This page exists so the gaps stay visible rather than being',
  'quietly forgotten.',
  '',
  `**${ideas.length} ideas indexed · ${sources.digs.filter((d) => d.status === 'pending').length} passes still outstanding.**`,
  '',
  '| Pass | Status | Yielded | What is in it |',
  '|---|---|---|---|',
  ...sources.digs.map((d) => {
    const y = ideas.filter((i) => i.source === d.id).length;
    const status = d.status === 'complete' ? 'complete' : d.status === 'open' ? 'open' : 'pending';
    return `| ${d.label} | ${status} | ${y} | ${d.detail} |`;
  }),
  '',
  '## By outcome',
  '',
  '| Outcome | Count |',
  '|---|---|',
  ...tax.raw.outcomes.map((o) => `| \`${o.id}\` | ${ideas.filter((i) => i.outcome === o.id).length} |`),
  '',
  'Every idea carries a `source` field naming its pass, so "what did this pass actually yield?" is',
  'a query rather than an archaeology project.',
]);

// ---------------------------------------------------------------------------
mkdirSync(OUT, { recursive: true });
const written = [];
for (const [name, content] of Object.entries(pages)) {
  writeFileSync(join(OUT, `${name}.md`), content.endsWith('\n') ? content : content + '\n', 'utf8');
  written.push(`${name}.md`);
}

// _Sidebar renders on every page.
writeFileSync(join(OUT, '_Sidebar.md'), [
  BANNER, '',
  '### idea-library',
  '',
  '- [Home](Home)',
  '- [Catalog](Catalog)',
  '- [Mechanics](Mechanics)',
  '',
  '**Reference**',
  '- [Idea Schema](Idea-Schema)',
  '- [Taxonomy](Taxonomy)',
  '- [Excavation Status](Excavation-Status)',
  '',
  '**Contributing**',
  '- [For AI Agents](For-AI-Agents)',
  '- [Bot Protocol](Bot-Protocol)',
  '- [Security Model](Security-Model)',
  '',
  `- [↩ repository](${REPO})`,
  '',
].join('\n'), 'utf8');
written.push('_Sidebar.md');

console.log(`wiki: wrote ${written.length} page(s) to ${OUT}`);
for (const w of written) console.log(`  + ${w}`);
console.log('\nNext: commit and push from the wiki clone.');
